### ISSUE TITLE
About `ipsc_labelling_tool/labelImg.py`

### ISSUE THREAD

**Issue by SZ-qing** [abhineet123/ipsc_prediction#1]
Hello, Thank you very much for this nice idea, the error I got when using labelimg. I installed your prompt in `https://github.com/abhineet123/ipsc_prediction/tree/master/ipsc_labelling_tool` and installed all the packages in the python3.7 environment, but there are two errors about importing modules when running:
There is **no hed_cv module** in line 181 of the script labelImg.py, and there is **no MTF module** in line 11, can you help me solve it?

**Comment by abhineet123** [comment]
Both HED and MTF are optional modules that are not required for any of the functionality used in this project. They had been added earlier for another project.

The tool should work fine without them. 
If it is not starting, there must be another error after the messages stating that these two are not available.

HED is the [holistically-nested edge detection module in OpenCV](https://github.com/opencv/opencv/blob/master/samples/dnn/edge_detection.py) and used to generate an initial rough mask for manual refinement.
The hed_cv module is available [here](https://drive.google.com/file/d/1fZ8Tb4O7fU2KzfY-3Lu-IFqUSlm6B8it). It was adapted from [this repo](https://github.com/acarcher/hed-opencv-dl).

MTF is a [tracking library](https://github.com/abhineet123/MTF) that can be used to add additional trackers for propagating labeled objects across frames.

**Comment by SZ-qing** [comment]
Thanks!!
