### ISSUE TITLE
Confused with eval_det.py's parameters

### ISSUE THREAD

**Issue by cell-lives** [abhineet123/ipsc_prediction#3]
Hello, thanks for your novel work. 

I am reproducing your work, but I am confused with eval_det.py's parameters. For example,  in order to evaluate SWD results, will run the fellow commands:

```shell
python3 eval_det.py cfg=ipsc_2_class img_paths=lists/ext_reorg_roi.txt det_paths=log/swi/ipsc_2_class_ext_reorg_roi_g2_16_53-no_validate/g2_0_15/csv gt_csv_name=annotations_0_15.csv save_suffix=inv-swi gt_pkl=g2_0_15.pkl iw=0 n_proc=12 iw=1
``` 

The argument, `gt_pkl`, need a pickle file. But I don't know how to produce this file. Also, before evaluating results, I have run the fellow commands:
```shell
python3 tools/test.py config=configs/swin/ipsc_2_class_ext_reorg_roi_g2_16_53-no_validate.py checkpoint=work_dirs/ipsc_2_class_ext_reorg_roi_g2_16_53-no_validate/epoch_3273.pth eval=bbox,segm test_name=g2_0_15
```

Would you please tell me how to produce the pickle file used by `gt_pkl`?
Thank you very much!

**Comment by abhineet123** [comment]
The GT pkl file is not necessary to run the evaluation.
It is an optional feature to speed up subsequent evaluation runs that use the same ground truth. 

Just remove the `gt_pkl=g2_0_15.pkl` part from the command and it will read the ground truth from the CSV files and generate the pkl file for later use.

Also, you need to either create a softlink to the  `ipsc_static_segmentation/swin_detection/work_dirs` folder to `ipsc_data_processing/log/swi` or change the `det_paths` parameter to point to this folder.

**Comment by cell-lives** [comment]
Oh, I know. Thanks!
