### ISSUE TITLE
About server.py error

### ISSUE THREAD

**Issue by SZ-qing** [abhineet123/ipsc_prediction#5]
Hello, when i use the function `Track All object` in labellmage tool, error is 
![image](https://github.com/abhineet123/ipsc_prediction/assets/85827219/ca43a781-d3b5-488f-8fe2-d18561f00308)

![image](https://github.com/abhineet123/ipsc_prediction/assets/85827219/9fc2ebc5-fe8e-499b-b132-646b0646dfe1)

I also open the terminal with the command line: 
`python tracking/Server.py --cfg=tracking/cfg/params.cfg --patch_tracker.tracker_type=3`
![image](https://github.com/abhineet123/ipsc_prediction/assets/85827219/98a298ec-d3d1-44ce-ac9f-b62eb1aecb49)

**Comment by abhineet123** [comment]
Please uncomment line 224 in labelImg.py: `self.start_server_thread()` (or pull the updated code from the repo).

Sorry, I apparently commented it out for debugging and forgot to uncomment.

Also, you don't need to start the tracking server to track objects if `tracking_mode ` parameter (line 3768 in labelImg.py) is set to 2.

**Comment by SZ-qing** [comment]
Thanks!
By the way, line 3701 in labelImg.py `label, points, _, _, difficult, bbox_source, id_number, score, _, _ = shape` , **shape** has 12 elements but just passed to 10 variables,  I added two extra variables and the `save csv` function works fine. Please help to confirm.

**Comment by abhineet123** [comment]
Yes, you're right. 
`PascalVocReader` shapes have two extra entries if it is initialized with `enable_hierarchy` turned on.

I've fixed this bug in the latest commit.

Thanks for pointing it out !
