### ISSUE TITLE
About training time spent 

### ISSUE THREAD

**Issue by SZ-qing** [abhineet123/ipsc_prediction#6]
Hi, I want to repeat your article, and I would like to ask you how long you trained for each part of static  images and videos.

**Comment by abhineet123** [comment]
Sorry, I'm not sure I entirely understand your question. 

If you're asking about how many epochs each model was trained for, you can find this info in the name of the checkpoint.

For example, early and late-stage SWD models were trained for 3273 and 2058 epochs and their checkpoints are therefore named `epoch_3273.pth` and `epoch_2058.pth` respectively

**Comment by SZ-qing** [comment]
What I want to ask is how long does it take to train the eight models based on your computing resources and parameter settings

---- Replied Message ----
| From | Abhineet ***@***.***> |
| Date | 08/11/2023 03:30 |
| To | abhineet123/ipsc_prediction ***@***.***> |
| Cc | SZ-qing ***@***.***>,
Author ***@***.***> |
| Subject | Re: [abhineet123/ipsc_prediction] About training time spent (Issue #6) |

Sorry, I'm not sure I entirely understand your question.

If you're asking about how many epochs each model was trained for, you can find this info in the name of the checkpoint.

For example, early and late-stage SWD models were trained for 3273 and 2058 epochs and their checkpoints are therefore named epoch_3273.pth and epoch_2058.pth respectively

**Comment by abhineet123** [comment]
That is hard to say but I'd guess at an average of 1 to 2 weeks per model.

The classifiers were the fastest to train and reached convergence in just 3 - 4 days while  the video segmentation models took the longest.

**Comment by SZ-qing** [comment]
Thanks.
---- Replied Message ----
| From | Abhineet ***@***.***> |
| Date | 08/11/2023 03:48 |
| To | ***@***.***> |
| Cc | SZ-qing ***@***.***>,
Author ***@***.***> |
| Subject | Re: [abhineet123/ipsc_prediction] About training time spent (Issue #6) |

That is hard to say but I'd guess at an average of 1 to 2 weeks per model.

The classifiers were the fastest to train and reached convergence in just 3 - 4 days while the video segmentation models took the longest.
